version: '3'
services:
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    restart: always
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo_db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    restart: always  
  notes-app:
    build: .
    ports:
      - 8080:3000
    restart: always
volumes:
  mongo-data:
    driver: local
